### ISSUE TITLE
wkhtmltopdf-installer wkhtmltopdf.exe` binary doesn't seem to work correctly issue

### ISSUE THREAD

**Issue by arupbaroi** [pofider/node-wkhtmltopdf-installer#9] opened 2018-03-21 08:45 UTC
I have this in my package.json file:

{
"name": "pdf",
"version": "1.0.0",
"description": "",
"main": "index.js",
"dependencies": {
"jsreport-core": "^1.3.1",
"jsreport-phantom-pdf": "^1.4.4",
"jsreport-jsrender": "^1.0.2",
"jsreport-wkhtmltopdf": "^1.4.0",
"jsreport-handlebars": "^1.1.2"
},
"devDependencies": {},
"scripts": {
"test": "echo "Error: no test specified" && exit 1"
},
"author": "",
"license": "ISC"
}

When I run npm install , I am getting this error

wkhtmltopdf-installer@0.3.1 postinstall C:\app\node_modules\wkhtmltopdf-installer
node lib/install.js

‼ Global command wkhtmltopdf doesn't seem to work. Downloading wkhtmltopdf localy to /vendor ...
× Error: The C:\app\node_modules\wkhtmltopdf-installer\vendor\wkhtmltopdf.exe binary doesn't seem to work correctly
at BinWrapper. (C:\app\node_modules\bin-wrapper\index.js:156:7)
at ChildProcess. (C:\app\node_modules\bin-check\index.js:26:4)
at emitTwo (events.js:126:13)
at ChildProcess.emit (events.js:214:7)
at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
Try running vendor/wkhtmltopdf to get more detailed error output.
npm notice created a lockfile as package-lock.json. You should commit this file.

Node version 8.9.0
I am running it with microsoft/aspnetcore:2.0-nanoserver-sac2016 docker image as base with node installed.

**Comment by pofider** [comment] 2018-03-21 09:13
Duplicate of https://github.com/jsreport/jsreport-wkhtmltopdf/issues/11

**Closed as completed by pofider** 2018-03-21 09:13 UTC

**Comment by arupbaroi** [comment] 2018-03-21 09:27
I am raising a new issue because the actual issue it not resolve. Please close at one place where it is duplicate not on both place when the issue is not resolve yet. :)
https://github.com/pofider/node-wkhtmltopdf-installer/issues/10

**Comment by pofider** [comment] 2018-03-21 09:28
It is not closed on both places.

**Comment by arupbaroi** [comment] 2018-03-21 09:30
Sorry it is my mistake. I will appreciate any fix for the issue. I am running out of time and idea how to fix this.

**Comment by pofider** [comment] 2018-03-21 09:31
I gave you the advice [here](https://github.com/jsreport/jsreport-wkhtmltopdf/issues/11#issuecomment-374855607). How did it end up?

**Comment by arupbaroi** [comment] 2018-03-21 10:26
I am using following code to generate report. Which is internally using wkhtmltopdf-installer inside jsreport_wkhtmltopdf package.

module.exports = function (callback, html) {
    var jsreport = require('jsreport-core')();

    jsreport.init().then(function () {
        return jsreport.render({
            template: {
                content: html,
                engine: 'jsrender',
                recipe: 'wkhtmltopdf'
            }
        }).then(function (resp) {
            callback(/* error */ null, resp.content.toJSON().data);
        });
    }).catch(function (e) {
        callback(/* error */ e, null);
    })
};
So downloading wkhtmltopdf manually will not work for me.

**Comment by pofider** [comment] 2018-03-21 10:29
The advice was about trying out wkhtmltopdf separately to find out if it actually works in windows nano server. Because it very likely doesn't.

**Comment by arupbaroi** [comment] 2018-03-21 10:50
I am able to do that. wkhtmltopdf is working fine with nano server. But not the wkhtmltopdf-installer

**Comment by pofider** [comment] 2018-03-21 10:52
This binary works also?
`C:\app\node_modules\wkhtmltopdf-installer\vendor\wkhtmltopdf.exe`?

**Comment by arupbaroi** [comment] 2018-03-21 10:57
did not get. Are you asking to install this exe in my docker image?

**Comment by arupbaroi** [comment] 2018-03-21 11:47
I think I found the issue. Nano server will be able to execute 64 bit exe. But the exe file in vendor folder is 32 bit. Please confirm and can you replace it with 64 bit so that I can check once.

Current version of wkhtmltopdf is available with 64 bit.

**Comment by pofider** [comment] 2018-03-21 12:31
Hm. The current binary from vendor normally works on all kind of x64 machines.

**Comment by arupbaroi** [comment] 2018-03-22 08:16
Ya it will work because all current x64 machines also support x86 file format , but for that image only x64 bit is allowed. That is why phantomjs.exe is working fine in my image but not wkhtmltopdf.

**Comment by pofider** [comment] 2018-03-22 10:55
I did check and the wkhtmltopdf version this package includes is x64. It is the one from here
https://github.com/wkhtmltopdf/wkhtmltopdf/releases/0.12.3.2/
labeled as `wkhtmltox-0.12.3.2_msvc2013-win64.exe`
